repos:
- repo: local
  hooks:
  - id: gdformat
    name: gdformat
    description: format gdscript files
    entry: gdformat
    language: system
    types: [gdscript]
    pass_filenames: true
  - id: gdlint
    name: gdlint
    description: lint gdscript files
    entry: gdlint
    language: system
    types: [gdscript]
    pass_filenames: true
  - id: fmt
    name: fmt
    description: Format files with cargo fmt.
    entry: sh -c "cd rust; cargo fmt"
    language: system
    types: [rust]
    args: ["--"]
  - id: cargo-check
    name: cargo check
    description: Check the package for errors.
    entry: sh -c "cd rust; cargo check"
    language: system
    types: [rust]
    pass_filenames: false
  - id: clippy
    name: clippy
    description: Lint rust sources
    entry: sh -c "cd rust; cargo clippy"
    language: system
    args: ["--", "-D", "warnings"]
    types: [rust]
    pass_filenames: false

