name: "Godot"

on: [push]

jobs:
  execute-gut:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute GUT Unit Test
        uses: dorianpercic/godot-gut-ci@main
        with:
          godot_version: 4.2.2
          gut_params: -gconfig=res://gut_editor_config.json
          project_path: godot

