name: Linux Export

on: [push]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  CARGO_INCREMENTAL: 0

jobs:
  export-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1
      - uses: chickensoft-games/setup-godot@v1
        name: Setup Godot
        with:
          version: 4.2.2
          include-templates: true
          use-dotnet: false
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "rust -> target"
          cache-all-crates: "true"

      - name: Install just
        run: cargo install just

      - name: just Check
        run: just --version

      - name: Godot Check
        run: |
          godot --version

      - name: Godot Export
        run: |
          set -x
          touch godot/.godot/extension_list.cfg
          echo "res://rust.gdextension" >> godot/.godot/extension_list.cfg
          cargo build --manifest-path=rust/Cargo.toml
          just linux-release

  export-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1
      - uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: "22"
      - uses: chickensoft-games/setup-godot@v1
        name: Setup Godot
        with:
          version: 4.2.2
          include-templates: true
          use-dotnet: false
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "rust -> target"
          cache-all-crates: "true"

      - name: Install just
        run: cargo install just

      - name: just Check
        run: just --version

      - name: Godot Check
        run: |
          godot --version

      - name: Godot Export
        run: |
          set -x
          touch godot/.godot/extension_list.cfg
          echo "res://rust.gdextension" >> godot/.godot/extension_list.cfg
          godot --headless -q -e --quit
          echo "export/android/java_sdk_path = \"$(dirname $(dirname $(which java)))\"" >> ~/.config/godot/editor_settings-4.tres
          echo "export/android/android_sdk_path = \"$(pwd)/dependencies/android-sdk/\"" >> ~/.config/godot/editor_settings-4.tres
          export GODOT_ANDROID_KEYSTORE_RELEASE_PATH="$PWD/secrets/debug.keystore"
          export GODOT_ANDROID_KEYSTORE_RELEASE_USER="androiddebugkey"
          export GODOT_ANDROID_KEYSTORE_RELEASE_PASSWORD="android"
          just setup-android
          cargo build --manifest-path=rust/Cargo.toml
          just android-release
