name: Rust

on: [push]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  rust-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: rui314/setup-mold@v1
    - uses: mozilla-actions/sccache-action@v0.0.4
    - name: Rust Run tests
      run: cd rust; cargo build --release

  rust-clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: rui314/setup-mold@v1
    - uses: mozilla-actions/sccache-action@v0.0.4
    - name: Rust Clippy
      run: cd rust; cargo clippy

  rust-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: rui314/setup-mold@v1
    - uses: mozilla-actions/sccache-action@v0.0.4
    - name: Rust Run tests
      run: cd rust; cargo test

  rust-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: rui314/setup-mold@v1
    - uses: mozilla-actions/sccache-action@v0.0.4
    - name: Rust Format
      run: cd rust; cargo fmt -- --check
